services:
  go-server:
    container_name: go-server
    image: go-server
    build:
      dockerfile: dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - GO_ENV=docker

  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
